#!/usr/bin/env bash
# =============================================================================
# setup-fixture-server.sh — Actual Budget Integration Test Fixture Setup
# =============================================================================
#
# Creates a fresh disposable Actual Budget server instance for integration tests.
#
# Usage:
#   ./setup-fixture-server.sh                          # Normal mode
#   DRY_RUN=1 ./setup-fixture-server.sh                 # Preview without changes
#   ACTUAL_SERVER_PORT=5006 ./setup-fixture-server.sh   # Custom port
#
# Required environment (provided externally or generated by this script):
#   ACTUAL_SERVER_URL    — URL of the Actual server (or will be set by script)
#   ACTUAL_SECRET_KEY    — optional server secret/password; generated per run when absent
#   ACTUAL_BUDGET_NAME   — name for the test budget (default: "BalanceFrame Test Budget")
#
# Output (on success):
#   Writes the complete fixture provenance to .env.test without printing secrets
#
# Returns:
#   0 — success, fixture ready
#   1 — failure
# =============================================================================

set -euo pipefail

# ---- Config ----------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Defaults
ACTUAL_SERVER_PORT="${ACTUAL_SERVER_PORT:-5006}"
ACTUAL_SERVER_URL="${ACTUAL_SERVER_URL:-"http://localhost:${ACTUAL_SERVER_PORT}"}"
ACTUAL_SECRET_KEY="${ACTUAL_SECRET_KEY:-}"
ACTUAL_BUDGET_NAME="${ACTUAL_BUDGET_NAME:-"BalanceFrame Test Budget"}"
ACTUAL_SERVER_DATA_DIR="${ACTUAL_SERVER_DATA_DIR:-"$SCRIPT_DIR/.actual-server-data"}"

DRY_RUN="${DRY_RUN:-0}"

# ---- Helpers ---------------------------------------------------------------
info()  { printf "\033[36m[INFO]\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m[WARN]\033[0m %s\n" "$*"; }
error() { printf "\033[31m[ERROR]\033[0m %s\n" "$*" >&2; }
ok()    { printf "\033[32m[OK]\033[0m   %s\n" "$*"; }

run_or_dry() {
  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would execute: $*"
    return 0
  fi
  "$@"
}

cleanup_on_fail() {
  warn "Fixture setup failed — cleaning up..."
  stop_actual_server
  exit 1
}

trap cleanup_on_fail ERR

# ---- Step 1: Check dependencies --------------------------------------------
check_deps() {
  info "Checking dependencies..."

  # The API client is used by the seed script; the server is provided by Nix.
  if ! command -v actual-server &>/dev/null; then
    error "actual-server is required; enter nix develop or provide a compatible server"
    exit 1
  fi
  ok "actual-server $(actual-server --version 2>/dev/null || true)"

  # Node.js is required by the Actual API seed script
  if ! command -v node &>/dev/null; then
    error "Node.js is required but not found in PATH"
    exit 1
  fi
  ok "Node.js $(node --version)"

  # pnpm provides the workspace dependency resolution for the seed script
  if ! command -v pnpm &>/dev/null; then
    error "pnpm is required but not found in PATH"
    exit 1
  fi
  ok "pnpm available"

  # curl for API health checks
  if ! command -v curl &>/dev/null; then
    error "curl is required but not found in PATH"
    exit 1
  fi
  ok "curl available"

  # jq for JSON parsing
  if ! command -v jq &>/dev/null; then
    warn "jq not found — will use node for JSON parsing"
  else
    ok "jq available"
  fi
}

ensure_secret_key() {
  if [ -n "$ACTUAL_SECRET_KEY" ]; then
    ok "Using caller-supplied Actual server secret (redacted)"
    return
  fi

  ACTUAL_SECRET_KEY="$(
    node -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('hex'))"
  )"
  if [ -z "$ACTUAL_SECRET_KEY" ]; then
    error "Could not generate the Actual server secret"
    return 1
  fi
  ok "Generated a fresh Actual server secret (redacted)"
}

# ---- Step 2: Stop a fixture server previously started by this script --------
stop_actual_server() {
  info "Checking for a fixture server previously started by this script..."

  local pid=""
  if [ -f "$SERVER_PID_FILE" ]; then
    pid="$(cat "$SERVER_PID_FILE")"
  fi

  if [ -z "$pid" ]; then
    local port_pid
    port_pid=$(lsof -ti "tcp:${ACTUAL_SERVER_PORT}" 2>/dev/null || true)
    if [ -n "$port_pid" ]; then
      warn "Port $ACTUAL_SERVER_PORT is occupied by unmanaged PID $port_pid."
      warn "Refusing to stop an existing server without $SERVER_PID_FILE."
      if [ "$DRY_RUN" = "1" ]; then
        return 0
      fi
      error "Choose another ACTUAL_SERVER_PORT or stop the existing server explicitly."
      return 1
    fi
    info "No managed fixture server found."
    return 0
  fi

  if ! kill -0 "$pid" 2>/dev/null; then
    warn "Removing stale fixture PID file for PID $pid."
    rm -f "$SERVER_PID_FILE"
    return 0
  fi

  local command_line
  command_line=$(ps -p "$pid" -o args= 2>/dev/null || true)
  if [[ "$command_line" != *actual-server* ]]; then
    error "PID file $SERVER_PID_FILE points to non-Actual process (PID $pid)."
    return 1
  fi

  info "Stopping managed Actual server (PID $pid) on port $ACTUAL_SERVER_PORT..."
  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would execute: kill $pid"
    return 0
  fi

  kill "$pid" 2>/dev/null || true
  for _ in $(seq 1 10); do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$SERVER_PID_FILE"
      ok "Managed fixture server stopped"
      return 0
    fi
    sleep 0.5
  done

  warn "Managed server did not stop gracefully; sending SIGKILL."
  kill -9 "$pid" 2>/dev/null || true
  rm -f "$SERVER_PID_FILE"
}

# ---- Step 3: Create fixture data directory ---------------------------------
FIXTURE_DIR="$SCRIPT_DIR/../../protocol/fixtures"
FIXTURE_DATA_FILE="$FIXTURE_DIR/representative.json"

ensure_fixture_data() {
  info "Ensuring fixture data exists..."

  if [ ! -f "$FIXTURE_DATA_FILE" ]; then
    warn "Fixture data file not found at $FIXTURE_DATA_FILE"
    info "Creating minimal representative fixture data..."

    if [ "$DRY_RUN" = "1" ]; then
      info "[DRY_RUN] Would create $FIXTURE_DATA_FILE"
      return
    fi

    mkdir -p "$FIXTURE_DIR"

    # Generate representative fixture data using the canonical protocol shape
    cat > "$FIXTURE_DATA_FILE" << 'FIXX'
{
  "schemaVersion": "1",
  "actualVersion": "25.1.0",
  "snapshotDate": "2026-07-15T00:00:00Z",
  "accounts": [
    { "id": "a_1", "name": "Checking Account", "accountType": "checking", "offBudget": false, "isClosed": false },
    { "id": "a_2", "name": "Savings Account", "accountType": "savings", "offBudget": false, "isClosed": false },
    { "id": "a_3", "name": "Credit Card", "accountType": "creditCard", "offBudget": false, "isClosed": false },
    { "id": "a_4", "name": "Cash Wallet", "accountType": "cash", "offBudget": true, "isClosed": false },
    { "id": "a_5", "name": "Investment Portfolio", "accountType": "investment", "offBudget": true, "isClosed": false },
    { "id": "a_6", "name": "Car Loan", "accountType": "loan", "offBudget": false, "isClosed": false }
  ],
  "categories": [
    { "id": "cat_1", "name": "Rent / Mortgage", "groupName": "Housing", "isIncome": false },
    { "id": "cat_2", "name": "Groceries", "groupName": "Food", "isIncome": false },
    { "id": "cat_3", "name": "Dining Out", "groupName": "Food", "isIncome": false },
    { "id": "cat_4", "name": "Gas / Fuel", "groupName": "Transportation", "isIncome": false },
    { "id": "cat_5", "name": "Public Transit", "groupName": "Transportation", "isIncome": false },
    { "id": "cat_6", "name": "Electric Bill", "groupName": "Utilities", "isIncome": false },
    { "id": "cat_7", "name": "Water Bill", "groupName": "Utilities", "isIncome": false },
    { "id": "cat_8", "name": "Internet", "groupName": "Utilities", "isIncome": false },
    { "id": "cat_9", "name": "Streaming Services", "groupName": "Entertainment", "isIncome": false },
    { "id": "cat_10", "name": "Movie / Events", "groupName": "Entertainment", "isIncome": false },
    { "id": "cat_11", "name": "Pharmacy", "groupName": "Healthcare", "isIncome": false },
    { "id": "cat_12", "name": "Doctor Visit", "groupName": "Healthcare", "isIncome": false },
    { "id": "cat_13", "name": "Emergency Savings", "groupName": "Savings", "isIncome": false },
    { "id": "cat_deleted", "name": "Old Category", "groupName": "Savings", "isIncome": false, "deleted": true },
    { "id": "cat_15", "name": "Business Travel", "groupName": "Transportation", "isIncome": false },
    { "id": "cat_16", "name": "Gifts", "groupName": "Entertainment", "isIncome": false }
  ],
  "payees": [
    { "id": "pay_1", "name": "AMAZON MKTPLACE", "transferAccountId": null },
    { "id": "pay_2", "name": "Amazon Marketplace", "transferAccountId": null },
    { "id": "pay_3", "name": "Whole Foods", "transferAccountId": null },
    { "id": "pay_4", "name": "Shell Gas Station", "transferAccountId": null },
    { "id": "pay_5", "name": "City Electric Co", "transferAccountId": null },
    { "id": "pay_6", "name": "Netflix", "transferAccountId": null },
    { "id": "pay_7", "name": "Spotify", "transferAccountId": null },
    { "id": "pay_8", "name": "Landlord Property Mgmt", "transferAccountId": null },
    { "id": "pay_9", "name": "Starbucks", "transferAccountId": null },
    { "id": "pay_10", "name": "Target", "transferAccountId": null },
    { "id": "pay_11", "name": "CVS Pharmacy", "transferAccountId": null },
    { "id": "pay_12", "name": "Uber", "transferAccountId": null },
    { "id": "pay_13", "name": "Home Depot", "transferAccountId": null },
    { "id": "pay_14", "name": "Costco Wholesale", "transferAccountId": null },
    { "id": "pay_15", "name": "Best Buy", "transferAccountId": null },
    { "id": "pay_16", "name": "ATM Withdrawal", "transferAccountId": null },
    { "id": "pay_17", "name": "Direct Deposit - Employer", "transferAccountId": null },
    { "id": "pay_18", "name": "Checking <> Credit Card", "transferAccountId": "a_3" },
    { "id": "pay_19", "name": "Checking <> Savings", "transferAccountId": "a_2" },
    { "id": "pay_20", "name": "Checking <> Loan", "transferAccountId": "a_6" },
    { "id": "pay_21", "name": "Comcast Cable", "transferAccountId": null },
    { "id": "pay_22", "name": "City Water Dept", "transferAccountId": null }
  ],
  "transactions": [
    { "id": "tx_000", "accountId": "a_1", "date": "2026-07-09", "payeeName": "Whole Foods", "categoryName": "Groceries", "amount": { "minorUnits": "-1500", "currency": "USD" }, "cleared": true, "notes": "Weekly groceries" },
    { "id": "tx_001", "accountId": "a_2", "date": "2026-07-08", "payeeName": "Shell Gas Station", "categoryName": "Gas / Fuel", "amount": { "minorUnits": "-2300", "currency": "USD" }, "cleared": true, "notes": null },
    { "id": "tx_002", "accountId": "a_3", "date": "2026-07-12", "payeeName": "City Electric Co", "categoryName": "Utilities", "amount": { "minorUnits": "-3500", "currency": "USD" }, "cleared": true, "notes": null },
    { "id": "tx_003", "accountId": "a_1", "date": "2026-07-11", "payeeName": "Netflix", "categoryName": "Entertainment", "amount": { "minorUnits": "-4200", "currency": "USD" }, "cleared": true, "notes": null },
    { "id": "tx_004", "accountId": "a_1", "date": "2026-07-15", "payeeName": "Direct Deposit - Employer", "categoryName": null, "amount": { "minorUnits": "500000", "currency": "USD" }, "cleared": true, "notes": "Monthly salary" },
    { "id": "tx_005", "accountId": "a_1", "date": "2026-07-10", "payeeName": "Starbucks", "categoryName": "Dining Out", "amount": { "minorUnits": "-750", "currency": "USD" }, "cleared": true, "notes": null },
    { "id": "tx_006", "accountId": "a_4", "date": "2026-07-14", "payeeName": "ATM Withdrawal", "categoryName": null, "amount": { "minorUnits": "-20000", "currency": "USD" }, "cleared": true, "notes": null },
    { "id": "tx_007", "accountId": "a_1", "date": "2026-07-12", "payeeName": "Checking <> Credit Card", "categoryName": null, "amount": { "minorUnits": "-150000", "currency": "USD" }, "cleared": true, "notes": "Credit card payment" },
    { "id": "tx_008", "accountId": "a_6", "date": "2026-07-15", "payeeName": "Checking <> Loan", "categoryName": null, "amount": { "minorUnits": "-50000", "currency": "USD" }, "cleared": true, "notes": "Loan installment" }
  ],
  "rules": [],
  "schedules": [],
  "budgets": [],
  "tags": []
}
FIXX
    ok "Fixture data created at $FIXTURE_DATA_FILE"
  else
    ok "Fixture data found at $FIXTURE_DATA_FILE"
  fi
}

# ---- Step 4: Start Actual server -------------------------------------------
SERVER_CACHE_DIR="$ACTUAL_SERVER_DATA_DIR"
SERVER_PID_FILE="$ACTUAL_SERVER_DATA_DIR/.actual-server.pid"
SEED_DATA_DIR="$ACTUAL_SERVER_DATA_DIR/seed-data"
SEED_RESULT_JSON=""

start_actual_server() {
  info "Starting Actual server..."

  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would start Actual server on port $ACTUAL_SERVER_PORT"
    info "[DRY_RUN]   with data directory: $SERVER_CACHE_DIR"
    return
  fi

  mkdir -p "$SERVER_CACHE_DIR/server-files" "$SERVER_CACHE_DIR/user-files"

  # Actual's published server is a separate executable from @actual-app/api.
  # Configuration is supplied through the documented ACTUAL_* environment
  # variables; the API client password is applied by the seed script.
  ACTUAL_PORT="$ACTUAL_SERVER_PORT" \
  ACTUAL_DATA_DIR="$SERVER_CACHE_DIR" \
  ACTUAL_SERVER_FILES="$SERVER_CACHE_DIR/server-files" \
  ACTUAL_USER_FILES="$SERVER_CACHE_DIR/user-files" \
    actual-server >"$SERVER_CACHE_DIR/server.log" 2>&1 &
  local server_pid=$!
  echo "$server_pid" > "$SERVER_PID_FILE"

  info "Waiting for server to become ready..."
  for i in $(seq 1 30); do
    if curl -s "${ACTUAL_SERVER_URL}/health" >/dev/null 2>&1; then
      ok "Actual server is ready at $ACTUAL_SERVER_URL (PID $server_pid)"
      return 0
    fi
    sleep 1
  done

  error "Server did not become ready within 30 seconds"
  cat "$SERVER_CACHE_DIR/server.log" >&2 || true
  kill "$server_pid" 2>/dev/null || true
  return 1
}

initialize_actual_password() {
  export ACTUAL_SECRET_KEY
  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would initialize Actual server password"
    return
  fi

  info "Initializing Actual server password..."
  export ACTUAL_PORT="$ACTUAL_SERVER_PORT"
  export ACTUAL_DATA_DIR="$SERVER_CACHE_DIR"
  export ACTUAL_SERVER_FILES="$SERVER_CACHE_DIR/server-files"
  export ACTUAL_USER_FILES="$SERVER_CACHE_DIR/user-files"

  # Reset while the server is stopped so the next process observes the new
  # password instead of retaining the previous account database in memory.
  stop_actual_server
  if ! expect <<'EXPECT'
    set timeout 30
    log_user 0
    spawn actual-server --reset-password
    expect -re "Enter a password, then press enter:" {
      send -- "$env(ACTUAL_SECRET_KEY)"
      after 500
      send -- "\r"
    }
    expect -re "Enter the password again, then press enter:" {
      send -- "$env(ACTUAL_SECRET_KEY)"
      after 500
      send -- "\r"
    }
    expect {
      -re "Password (set|changed)!" {
        expect eof
        exit 0
      }
      -re "Passwords do not match." {
        exit 1
      }
      eof {
        exit 1
      }
    }
EXPECT
  then
    error "Actual server password initialization failed"
    return 1
  fi
  start_actual_server
  ok "Actual server password initialized"
}

# ---- Step 5: Create and seed the test budget --------------------------------
SEED_SCRIPT="$SCRIPT_DIR/seed-budget.mjs"

verify_seed_script() {
  info "Checking checked-in seed script..."

  if [ ! -f "$SEED_SCRIPT" ]; then
    error "Checked-in seed script not found at $SEED_SCRIPT"
    return 1
  fi
  if [ ! -r "$SEED_SCRIPT" ]; then
    error "Checked-in seed script is not readable at $SEED_SCRIPT"
    return 1
  fi

  ok "Seed script found at $SEED_SCRIPT"
}

seed_budget() {
  info "Creating and seeding test budget..."
  info "  Server: $ACTUAL_SERVER_URL"
  info "  Budget: $ACTUAL_BUDGET_NAME"

  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would seed budget with fixture data from $FIXTURE_DATA_FILE"
    return
  fi

  rm -rf "$SEED_DATA_DIR"
  mkdir -p "$SEED_DATA_DIR"

  local seed_output
  seed_output=$(
    ACTUAL_SERVER_URL="$ACTUAL_SERVER_URL" \
    ACTUAL_SECRET_KEY="$ACTUAL_SECRET_KEY" \
    ACTUAL_BUDGET_NAME="$ACTUAL_BUDGET_NAME" \
    FIXTURE_DATA_PATH="$FIXTURE_DATA_FILE" \
    SEED_DATA_DIR="$SEED_DATA_DIR" \
      node "$SEED_SCRIPT"
  )
  printf '%s\n' "$seed_output"
  SEED_RESULT_JSON="${seed_output##*$'\n'}"

  ok "Budget seeded successfully"
}

# ---- Step 6: Output environment variables ----------------------------------
output_env() {
  local env_file="$SCRIPT_DIR/.env.test"
  if [ "$DRY_RUN" = "1" ]; then
    info "[DRY_RUN] Would write fixture environment to $env_file"
    info "[DRY_RUN] Actual server secret: (redacted)"
    return
  fi

  local seed_output="$SEED_RESULT_JSON"
  local budget_id
  budget_id=$(echo "$seed_output" | jq -r '.budgetId // empty' 2>/dev/null || echo "")
  local group_id
  group_id=$(echo "$seed_output" | jq -r '.groupId // empty' 2>/dev/null || echo "")

  if [ -z "$budget_id" ] || [ -z "$group_id" ]; then
    error "Could not extract budget/group ID from seed output"
    return 1
  fi

  quote_env_value() {
    local value="$1"
    if [[ "$value" == *"'"* || "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
      error "Fixture environment values cannot contain single quotes or line breaks"
      return 1
    fi
    printf "'%s'" "$value"
  }

  local qm qs qk qb qg qn qsd
  qm="$(quote_env_value "1")"
  qs="$(quote_env_value "$ACTUAL_SERVER_URL")"
  qk="$(quote_env_value "$ACTUAL_SECRET_KEY")"
  qb="$(quote_env_value "$budget_id")"
  qg="$(quote_env_value "$group_id")"
  qn="$(quote_env_value "$ACTUAL_BUDGET_NAME")"
  qsd="$(quote_env_value "$SEED_DATA_DIR")"

  umask 077
  cat > "$env_file" << ENV
BALANCEFRAME_ACTUAL_FIXTURE=$qm
ACTUAL_SERVER_URL=$qs
ACTUAL_SECRET_KEY=$qk
ACTUAL_BUDGET_ID=$qb
ACTUAL_GROUP_ID=$qg
ACTUAL_BUDGET_NAME=$qn
ACTUAL_SEED_DATA_DIR=$qsd
ENV
  chmod 0600 "$env_file"

  ok "Environment written to $env_file"
  info "Actual server secret: (redacted)"
}

# ---- Main ------------------------------------------------------------------
main() {
  echo ""
  info "=== BalanceFrame Actual Integration Test Fixture Setup ==="
  echo ""
  info "Mode: $([ "$DRY_RUN" = "1" ] && echo "DRY RUN (preview)" || echo "LIVE")"
  echo ""

  check_deps
  ensure_secret_key
  echo ""
  echo ""
  stop_actual_server
  echo ""
  ensure_fixture_data
  echo ""
  start_actual_server
  echo ""
  initialize_actual_password
  echo ""
  verify_seed_script
  echo ""
  seed_budget
  echo ""
  output_env

  echo ""
  ok "Fixture setup complete!"
  echo ""
  info "Load $SCRIPT_DIR/.env.test to run the integration tests (secret redacted)"
  echo ""
}

main
